### PR TITLE
Added method to search members by status (subscribed, unsubscribed, c…

### PR DESCRIPTION
**Pull request by eamoralesl**
Added method to search members by status (subscribed, unsubscribed, cleaned) 
All tests running

### CODE REVIEW

**Comment by micheal-swiggs** [comment]
@eamoralesl Thanks for this! Looks good. I'm just wondering why you have created `MemberStatus` instead of using `SubscribeStatus`. Perhaps there is one way that we can have just one enum?

**Comment by eamoralesl** [comment]
Hi @micheal-swiggs I did try to use it but the API doesn't accept the member status for that call in uppercase just lowercase, do you have a suggestion on how to use the same enum for both?

**Comment by micheal-swiggs** [comment]
It might be worth testing this: https://github.com/OpenFeign/feign#custom-param-expansion .

**Comment by eamoralesl** [comment]
Implemented the param expander, now using only one enum

**Pull request merged**
