### PR TITLE
simplified requests and added entity properties

### PR DESCRIPTION
**Pull request by stevensnoeijen**
Hi,
I've changed/added alot in the lib and would like to contribute it to the community.

The total sumary of changes:
- chg: updated feign version
- chg: replaced feign-jackson with own encoder/decoder to support an older version of jackson
- new: MailChimpClient.getRoot .getLists
- chg: combined Create/Default classes with the "base"-class (like Member)
- new: custom MailChimpErrorException (extends FeignException) and ErrorDecoder
- fix: decode 404 as null (like when user can not be found in a list)
- chg: moved constants to the @JsonProperty
- chg: renamed Contact to AccountContact, MemberCreateBatch to CreateBatch, MemberList to List
- new: added Batches and Lists
- chg: added all properties and setters (when valid) to Member, List, ListStats
- new: add entities: ListContact, Root
- chg: added all types to MergeType
- chg: simplifield SubscribeStatus
- fix: set Member.timestampSignup wasnt serialized correctly
- chg: Date to ZonedDateTime and updated (de)serializer
- new: (partly) tests MailChimpClient methods
- new: InSequence testing for MailChimpClient, so stuff can be cleaned up afterwards

### CODE REVIEW

**Comment by snoein** [comment]
bump

**Comment by micheal-swiggs** [comment]
@stevensnoeijen Thanks for this. I'll review it within the next few days.

**Comment by micheal-swiggs** [comment]
@stevensnoeijen lots of new stuff! Can you please change the name of the class src/main/java/com/mailchimp/domain/List.java so that it's not the same as java.util.List. Also it looks like the statusIfNew field has been removed from the Member.java class. Is there a reason for this?

**Comment by snoein** [comment]
I'll rename the List class and add statusIfNew again (I probably removed it because its not documented properly)

**Comment by snoein** [comment]
applied your requests :)

**Pull request merged**
